### PR TITLE
rebrand to AdaLite

### LINKED ISSUE #193: Rebrand to AdaLite

### PR DESCRIPTION
**Pull request by git-jano**
rebrand CardanoLite -> AdaLite
to be done:
[ ] update github wiki FAQ page name
[ ] create appropriate email address 
[ ] rename trezor affiliate link

closes #193

### CODE REVIEW

**Comment by gazhayes** [comment]
Was this because of some kind of complaint from Cardano Foundation? If so I'd like to know the specifics.

**Comment by MichalPetro** [comment]
> Was this because of some kind of complaint from Cardano Foundation? If so I'd like to know the specifics.

We had conversations with Cardano Foundation and they asked not to use word Cardano in our brand. They offered several alternatives. It was more of a request than a demand but with decided to comply.

**Comment by vantuz-subhuman** [comment]
> and they asked not to use word Cardano in our brand

Oh, man, I am so so sorry to hear that - facepalm.jpg

Your are doing god's work here, guys, community appreciates

**Comment by Nykho** [comment]
oh god 😠 you shouldn’t have to go through this... i’m really sorry

**Comment by MichalPetro** [comment]
Actually they kindly asked us to do so, it was our decision to comply in the end.

And they allowed us to use AdaLite so we are fine, AdaLite.io is cool :)

**Pull request merged**
