### PR TITLE
reorganized folder structure

### PR DESCRIPTION
**Pull request by refi93**
check if new folder structure makes sense and if .gitignore, linting, running server, is set right

### CODE REVIEW

**Comment by ddeath** [comment]
I would move `svg.js` into `components/common` folder

**Comment by git-jano** [comment]
/navbar/exportWalletDialog.js might go up, it is triggered by a button in navbar, but the action is not related to navbar

**Comment by git-jano** [comment]
why is landing page at top level and not in client? i suggest put it in frontend

**Comment by git-jano** [comment]
what is /public/js for? semms empty even after build

**Comment by ddeath** [comment]
looks like `frontend/middleware.js` is unused so I suggest to delete it

**Comment by ddeath** [comment]
It seem that files `printAda.js`, `validators.js`, `debugLog.js` are just helpers so I suggest to move it to `wallet/helper` also maybe rename it to `utils`

**Comment by ddeath** [comment]
I would move `initialState` and `createStore` from `walletApp.js` to `store.js` - if you see in folder `actions.js` then you will probably also looking for `store.js`

**Pull request merged**
